name: 📦 Publish Provider

on:
  push:
    branches: [release/snap-provider]
jobs:
  publish-npm-registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - name: 📥 Install Dependencies
        run: yarn
        env:
          GH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
      - name: 🏗️ Build Library and Publish
        run: yarn build:provider && yarn publish:provider
        env:
          GH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  publish-gitHub-registry:
    runs-on: ubuntu-latest
    env:
      NEW_VERSION: ${{ github.ref_name }}
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: ⬇️ Checkout Repo
        uses: actions/checkout@v3

      - name: ⎔ Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'
          scope: '@leapwallet'

      - name: 📥 Install Dependencies
        run: yarn
        env:
          GH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}

      - name: 🏗️ Build Library
        run: yarn build:provider && yarn publish:provider
        env:
          GH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
